config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "/pages/:page" => "pages#show"
  get "/search" => "players#search"
  resources :players, only: %i[index show search]
  resources :teams, only: %i[index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  validates :first_name, presence: true
  validates :jersey_number, numericality: { only_integer: true }
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  validates :name, uniqueness: true
  validates :name, :abbreviation, :first_year, :conference, :division, :venue, :web_site,
            presence: true
  validates :first_year, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @teams = Team.all

    @players = Player.limit(10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[show edit update destroy]

  # GET /players or /players.json
  def index
    @players = Player.all.order("jersey_number").paginate(page: params[:page], per_page: 25)
  end

  # GET /players/1 or /players/1.json
  def show
    @player = Player.find(params[:id])
    @team = Team.find(@player.team_id)
  end

  def search
    @players = Player.where("full_name LIKE ?", "%" + params[:q] + "%")
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit; end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def player_params
    params.require(:player).permit(:full_name, :position, :position_abbreviation, :jersey_number)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[show]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
    @team = Team.find(params[:id])
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit; end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_team
    @team = Team.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def team_params
    params.require(:team).permit(:name, :abbreviation, :first_year, :conference, :division,
                                 :web_site)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<div class="columns mt-2 ml-2">
  <div class="column mt-5">
    <h2 class="title is-2">Teams</h2>
    <ul class="">
      <% @teams.each do | team | %>
        <li><%= link_to team.name , team %> <em>(Team Points)</em></li>
      <% end %>
    </ul>
  </div>

  <div class="column mt-5">
    <h2 class="title is-2">Players </h2>
    <ul class="">
      <% @players.each do | player | %>
        <li><%= link_to player.full_name, player %> <em>(Player Points)</em></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer" style="background: hsl(0, 0%, 21%); color: white;">
  <div class="content has-text-centered ">
    <p>
      <strong style="color: white;">Ruby on Rails NHL Project</strong> by Josh Lavallee.
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar is-dark is-mobile" style="min-height: 4.2rem" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://www.nhl.com/">
      <img src="https://i.pinimg.com/originals/a1/4c/52/a14c52ec2beb39f53d37a2337405b207.png" width="35" height="50" alt="nhl_logo">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="<%= root_path %>">
        Home
      </a>

      <a class="navbar-item">
        Standings
      </a>

      <a class="navbar-item" href="<%= teams_path %>">
        Teams
      </a>

      <a class="navbar-item" href="<%= players_path %>">
        Players
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            Contact
          </a>
          <a class="navbar-item" href="/pages/about">
            About
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NhlProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="title is-1 mt-2">About Page</h1>

<p class="mb-3">The data used in the creation of this was taken from the NHL Stats API.</p>

<p class="mb-3">The two datasets I used in order to create my AR models were from the Team and Roster endpoints. The JSON contained existing Primary and Foreign keys, so in order to associate each team with their roster, I used the existing PK to pull the players for that team in sequence before moving onto the next team. When assosciating the player within my Database I used the automatically created PK instead of the provided PK so the local data was related.</p>

<p class="mb-3">Team data consists of a PK team_id, team name, team abbreviation, venue, website, and the year they joined the league. All this data was validated as required and the year as integer_only to ensure no floating numbers are inserted to the database. All other columns were assigned as strings with presence required.</p>

<p class="mb-3">Player data consists of a PK player_id and FK of their corresponding team team_id. The data includes the players full name, jersey number, position, and position abbreviation. All columns were strings other than the jersey number which was an integer validated as only_integer. The only required column for this model was the full_name.</p>

<h2 class="title is-2 mt-2">ERD</h1>

<%= image_tag("nhl_erd.jpg", :alt => "ERD") %>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :position_abbreviation %>
    <%= form.text_field :position_abbreviation %>
  </div>

  <div class="field">
    <%= form.label :jersey_number %>
    <%= form.number_field :jersey_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title is-1 mt-2">Players</h1>

<table class="table">
  <thead>
    <tr>
      <th>Full name</th>
      <th>Position</th>
      <th>Position abbreviation</th>
      <th>Jersey number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.full_name, player %></td>
        <td><%= player.position %></td>
        <td><%= player.position_abbreviation %></td>
        <td><%= player.jersey_number %></td>
        <td><%= link_to 'Details', player %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/search.html.erb
<h1 class="mt-3 mb-3">Search Results For: <%= params[:q] %></h1>

<% if @players.empty? %>
  <h1>No Results Found.</h1>
<% else %>
<table class="table is-hoverable is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Full name</th>
      <th>Position</th>
      <th>Position abbreviation</th>
      <th>Jersey number</th>
      <th>Expand</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.full_name, player %></td>
        <td><%= player.position %></td>
        <td><%= player.position_abbreviation %></td>
        <td><%= player.jersey_number %></td>
        <td><%= link_to 'Details', player %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<p class="mt-2 mb-2">
  <strong><%= link_to "Back to players", :back %></strong>
</p>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<section class="card">
  <div class="card-image">
    <figure class="image is-2by1">
      <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
    </figure>
  </div>
<div class="level card-content">
<div class="title is-1 card-header-title"><%= @player.full_name %> | <%= @player.position %></div>
  <div class="level-item has-text-centered pt-0">
    <div>
      <p class="heading">Jersey Number</p>
      <p class="title"><%= @player.jersey_number %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Position</p>
      <p class="title"><%= @player.position_abbreviation %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Current Team</p>
      <p class="title"><%= @team.abbreviation %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Points</p>
      <p class="title">##</p>
    </div>
  </div>
</div>
</section>
<p class="mt-2 mb-2">
  <strong><%= link_to "Back to " + @team.abbreviation, @team %></strong>
</p>